### ISSUE TITLE
rewrite todo list

### ISSUE THREAD

**Issue by TheMoksej** [discordextremelist/bot#68]
This issue is mainly just for me to keep track of what I should do.

- [ ] Slash commands
- [ ] Moderation & Logging
- [ ] Automod
   - [ ] Anti raid
   - [x] Anti spam
   - [x] Anti invite
   - [x] Whitelist links to library/discord/our server(s)
- [x] Issue #48 
   - [x] Detect Discord token and upload it to gist
   - [x] Detect DELAPI token and send a message to the user (can't regenerate without having access to db)
- [x] Issue #54
   - [x] Automatically assign the common prefix role if prefix is in `!`, `-`, `.`, `?`, `*`, `,` list
   - [x] A command to add/remove the role
- [x] Issue #59
- [x] Issue #62 
   - [x] Default 48 hour countdown once the ticket status gets changed to "Awaiting fixes" by the moderator
   - [x] A command for a moderator to extend the timer
- [x] Issue #33 
- [x] Better ticket management commands (`add-user`, `remove-user`)
- [x] Reply with "Please don't mention staff" in tickets if staff gets mentioned
- [x] Remove 100 message history cap from tickets.
- [x] Allow someone to link an issue fast (basically what Pylon does)
   - [x] Respond with a link to an issue once the message is sent
- [x] Check if message contains questions about approval time and reply automatically with an answer
- [x] ~~If tag only has 1 language supported, don't ask for a reaction prompt~~ Possible but only with for loop, and that's unnecessary.
- [ ] Code improvements
   - [ ] Remove useless stuff

_If anyone has any suggestions for what else could be added to the bot, feel free to drop them below._

**Comment by TheMoksej** [comment]
I'll delay this a bit, expect this to be done at the end of this month or the beginning of the next month. Want to work on my projects I haven't worked on in a while

**Comment by carolinaisslaying** [comment]
Thanks for all your help moksej! I'm closing this now since it hasn't been touched in quite a while.
